classDiagram
    class A {
        -att0 : string
    }

    class Aext {
        -att1 : string
        -att2 : string(uuid)
        -enumeration : enum
    }

    class B {
        -att3 : string
    }

    class C {
        -att4 : string
    }

    class F {
        -att5 : string
    }

    class G {
        -att5 : string
    }

    class H {
        -att5 : string
    }

    class I {
        -att5 : string
    }

    class SpecD {
        -att5 : string
    }

    class SpecE {
        -att6 : string
    }

    class Multianyofrelation
    Multianyofrelation : <<abstract>>

    class Spec
    Spec : <<abstract>>

    Aext o-- "*" Multianyofrelation :  multi_anyof_relation
    Multianyofrelation <|-- I
    Multianyofrelation <|-- H
    Aext o-- "1" B :  single_relation
    Aext o-- "*" C :  multi_relation
    Aext o-- "1" Spec :  oneof_relation
    Spec <|-- SpecD
    Spec <|-- SpecE
    Aext o-- "*" Spec :  anyof_relation
    A <|-- Aext
