@startuml
class A {
    -employeenumber : string
    #uuid : string
    -oneof_relation : object
    -enumeration : enum
}
class B {
    -att1 : string
}
class C {
    -att1 : string
}
class D {
    -att1 : string
}
class E {
    -att1 : string
}
A o-- "1" B : single_relation
A o-- "*" C : multi_releatiion

@enduml